### ISSUE TITLE
速度が出ているときにあまり回転しないようにする

### ISSUE THREAD

**Issue by HansRobo** [ibis-ssl/crane#110]
これはロボット側で実装してもらうべきかも？
速度が出ているときに回転運動をするとVisionの遅れも相まってロボットの動きが乱れやすいので注意

**Comment by ChikuwaRobo** [comment]
おそらくロボット側のモーター出力制限によって、高速域や高加速度域で挙動が変になっていると思われる
モーター固有のパラメーターキャリブレーションもあまり賢くないのでそのへんの影響もあるかもしれない
いずれにせよロボット側で修正する

**Comment by HansRobo** [comment]
頼んだぞ〜

**Comment by HansRobo** [comment]
一旦AI側で対応してある
https://github.com/ibis-ssl/crane/pull/209/commits/5ce2304c42199f7e1d24056efa73b98f7abd9ab7
