### ISSUE TITLE
ふりーきっくをしない場合がある。

### ISSUE THREAD

**Issue by ssaattww** [ibis-ssl/crane#373]
# 再現方法
## 設定
- ロボット台数11台
- grSim, game-controllerはデフォルトの設定で実行
  - ```~/grsim/grSim/bin$ ./grSim```
  - ```~/ibis_ws/src/crane/docker$ sudo docker compose up -d```
  - ```source ~/ibis_ws/install/setup.bash && ros2 launch crane_bringup crane.launch.xml```
- https://github.com/ibis-ssl/crane/blob/86a2b74ed00b4a2bbc2959792481eada3f342593/crane_bringup/launch/crane.launch.xml#L43
  - これは1.0に設定
## 手順(game-controller)
1. kickoff blue (自チームのキックオフで開始)
2. blue goal
    - このとき中央にボール置き直す 
3. kickoff yellow
4. stop
5. free kick blue これでフリーキックしない
6. force start これでも近づけない。![Screenshot from 2024-05-19 22-22-10](https://github.com/ibis-ssl/crane/assets/36392290/1932134d-a455-4814-b7d6-b323e70cef2c)

**Comment by HansRobo** [comment]
@ssaattww 多分再現した
https://github.com/ibis-ssl/crane/assets/12395284/da0dfab0-ce26-47b6-8d41-305ddfe92e46

**Comment by ssaattww** [comment]
今度は微動だにしない・・・

**Comment by HansRobo** [comment]
最近見ないので一旦閉じます。
また発生したら再オープンか新しくIssueを作って対処しましょう
