### ISSUE TITLE
設定のパスを絶対パスから相対パスにしたい

### ISSUE THREAD

**Issue by ssaattww** [ibis-ssl/crane#423]
ユーザーネームを含む設定値がgit管理されているとちょっとめんどくさいので相対パスにするか、.vscodeをgitignoreに追加したい
gitignoreを見ると.vscodeをコメントアウトしている形跡があったのでなにか意図がありそうなのでそれも確認したい・・・

## 対応例
例えば[c_cpp_propaties.json](https://github.com/ibis-ssl/crane/blob/778e7004488128bbc8ea7984a1b0bf8fb132fa27/.vscode/c_cpp_properties.json#L9-L42)
以下のようにすれば、ユーザーネームは入り込まない

```json
  "${workspaceFolder}/session/crane_planner_plugins/include",
  "${workspaceFolder}/crane_robot_skills/include",
  "${workspaceFolder}/crane_game_analyzer/include",
  "${workspaceFolder}/session/crane_session_controller/include"
```

※
${workspaceFolder}は ```bis_ws/src/crane```
${workspaceFolder}/../install/ってすれば```bis_ws/install/crane```も指定できるかも

**Comment by HansRobo** [comment]
@ssaattww おお、これは不便をかけました。

> gitignoreを見ると.vscodeをコメントアウトしている形跡があったのでなにか意図がありそうなのでそれも確認したい・・・

vscodeの設定も置いておくと便利だよね...くらいしか考えていなかったと思う。
その時あった設定をそのまま追加したからあんまり一般化できていない

**Comment by HansRobo** [comment]
@ssaattww 
#424 これでどうだろうか？
ちなみに、vscodeは実はあまりつかっていないので、設定はもっと土鍋好みに変更してもらっても構わないよ
