### ISSUE TITLE
TIGERs 2016 ETDPを読む

### ISSUE THREAD

**Issue by HansRobo** [ibis-ssl/crane#435]
多分重要。ロボットとの通信やその周りの処理について書いてあるらしい

https://tdp.roboteamtwente.nl/tdps/168?ref=year

**Comment by ChikuwaRobo** [comment]
通信系ハードウェアの制約？によって送受信データサイズをかなり削っているっぽい。
skill IDによってデータの解釈を切り替えているのは1パケットごとのサイズを小さくするため？
今ウチで使っている仕組みだと、それなりにパケットサイズ大きくしても問題ないので真似する必要はないが、パケットの変更はしやすそう。

ロボット側からのフィードバックもしていそう。
curSpeedとかのcurはcurrent？
KickCountでキック回数を見て蹴ったかどうかを見ているのは面白い。

**Comment by HansRobo** [comment]
> skill IDによってデータの解釈を切り替えているのは1パケットごとのサイズを小さくするため？
今ウチで使っている仕組みだと、それなりにパケットサイズ大きくしても問題ないので真似する必要はないが、パケットの変更はしやすそう。

ここらへんはパケットサイズの低減というよりは、うちでも話している制御コマンドのモード切り替えという側面が大きそう
以下がTIGERsの基本スキルのラインナップ

- x,y,thetaを送るモード
- vx,vy,omegaを送るモード
- x,y,theta,vx,vy,omega全部送るモード

**Comment by ChikuwaRobo** [comment]
データサイズはあんまり変わってないか
制御パケットの見直しで考えていたことと同じなら、今の方針が妥当なんだなという自信がついてきた

**Comment by HansRobo** [comment]
モード切替はある程度実装して動作確認までできたのでクローズします
